---
# Ansible default connection variables
ansible_ssh_port: 5985
ansible_connection: "winrm"
ansible_winrm_server_cert_validation: "ignore"
ansible_winrm_transport: "ntlm"

# Ansible VM variables
install_iis: false
install_wcf: false
install_dotnetcore: false
install_dotnetfull: false
install_nssm: false
dotnetcore_version: "" # See https://chocolatey.org
dotnetfull_version: "" # See https://chocolatey.org
nssm_version: "" # See https://chocolatey.org


# Ansible VSTS project variables
vsts_poolname: "FinProd-PRD-EC2-App-Windows"
vsts_remove: false # Use true to uninstall